### PR TITLE
Troopattack closes #132

### LINKED ISSUE #132: New attack, show carry capacity
And maybe some other info when sending an attack on the troops you choose

### PR DESCRIPTION
**Pull request by Geczy**

### CODE REVIEW

**Comment by Geczy** [comment]
This also touches #129

**Comment by AleksandarDev** [comment]
This is working?

**Comment by Geczy** [comment]
Yeah. No fancy css

**Comment by AleksandarDev** [comment]
Please in future, request pulls for `development`  branch, master is only for store releases. Thanks

**Comment by Geczy** [comment]
Well the current master isn't a store release :p

**Comment by AleksandarDev** [comment]
That's my fault. Are you currently running on master branch? Can you please quick test it and let me know, I'll deploy new version to the store on your mark.

**Comment by Geczy** [comment]
Yeah im on master, the plugin page doesn't load remember?

**Comment by AleksandarDev** [comment]
If that is the only problem - great! I will take a look into that after work and will release it asap. Thanks!

**Comment by Geczy** [comment]
Might wanna switch the adventure and the new troop plugin from internal / beta to public? So they have access to it

**Comment by AleksandarDev** [comment]
Sure, will do.

**Pull request merged**
